---
- name: Install Nagios 3 on CentOS
  hosts: centos_servers
  become: yes
  tasks:
    - name: Update system packages
      dnf:
        name: '*'
        state: latest

    - name: Install required packages
      dnf:
        name:
          - gcc
          - glibc
          - glibc-common
          - perl
          - wget
          - unzip
          - httpd
          - php
          - gcc-c++
          - make
          - autoconf
          - automake
          - php-cli
          - php-gd
          - php-mbstring
          - php-mysqlnd
          - php-xml
          - httpd-tools
        state: present

    - name: Create Nagios user and group
      user:
        name: nagios
        shell: /sbin/nologin
        system: yes

    - name: Add Nagios user to Apache group
      user:
        name: nagios
        groups: apache
        append: yes

    - name: Download Nagios 3
      get_url:
        url: https://github.com/NagiosEnterprises/nagioscore/archive/refs/tags/3.5.1.tar.gz
        dest: /tmp/nagios.tar.gz

    - name: Extract Nagios
      unarchive:
        src: /tmp/nagios.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Compile and install Nagios
      command: >
        /bin/bash -c "cd /tmp/nagioscore-3.5.1 && ./configure --with-command-group=nagios && make all && make install && make install-init && make install-config && make install-commandmode"
      args:
        chdir: /tmp/nagioscore-3.5.1

    - name: Download Nagios Plugins
      get_url:
        url: https://github.com/NagiosEnterprises/nagios-plugins/archive/refs/tags/release-1.4.16.tar.gz
        dest: /tmp/nagios-plugins.tar.gz

    - name: Extract Nagios Plugins
      unarchive:
        src: /tmp/nagios-plugins.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Compile and install Nagios Plugins
      command: >
        /bin/bash -c "cd /tmp/nagios-plugins-release-1.4.16 && ./configure --with-nagios-user=nagios --with-nagios-group=nagios && make && make install"
      args:
        chdir: /tmp/nagios-plugins-release-1.4.16

    - name: Configure Nagios
      lineinfile:
        path: /usr/local/nagios/etc/nagios.cfg
        regexp: '^admin_email'
        line: 'admin_email=nagios@localhost'

    - name: Add Nagios admin user
      command: htpasswd -c /usr/local/nagios/etc/htpasswd.users nagiosadmin
      args:
        stdin: 'your_password_here'

    - name: Start and enable Nagios service
      systemd:
        name: nagios
        state: started
        enabled: yes

    - name: Start and enable Apache service
      systemd:
        name: httpd
        state: started
        enabled: yes
